language: node_js
env: TRAVIS_CI=true
node_js:
  - "4.2.4"
  - "5.9.0"
  - "6.3.0"
  - "6.9.1"
  - "7.2.0"
  - "8.9.3"
before_script:
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-(e.g.-a-Web-browser)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn run test:gulp
  - yarn run test
  - yarn run build
  - yarn run distribution
